### ISSUE TITLE
Error: cannot unmarshal number while scanning

### ISSUE THREAD

**Issue by elayaraja-kv** [confluentinc/schema-deletion-tool#6]
Trying to use this plugin with confluent cli and unable to, error as below

Scanning schemas under subject perf.contact-value...Error: json: cannot unmarshal number into Go struct field SchemaInfo.schema_id of type string

**Comment by msillence** [comment]
Looks like this PR fixes it https://github.com/confluentinc/schema-deletion-tool/pull/5
